Add multiview example
immersive-web/webxr-samples pull request #110
Opened 2021-05-22 01:30 UTC by fe1ixz

This PR adds the multiview sample with projection layer. @toji

2021-06-16 02:49 UTC, toji requested changes
Only a couple of minor points of feedback on this one, thanks!

2021-06-16 02:49 UTC, toji commented on layers-samples/proj-multiview.html
> +Copyright 2018 The Immersive Web Community Group
```suggestion
Copyright 2021 The Immersive Web Community Group
```

2021-06-16 02:49 UTC, toji commented on layers-samples/proj-multiview.html
> +    function create_depth_texture(width, height) {
Function seems like it's not used?

2021-06-16 02:49 UTC, toji commented on layers-samples/proj-multiview.html
> +            if (views.length == 0) { // for mutliview we need to set fbo only once
```suggestion
            if (views.length == 0) { // for multiview we need to set fbo only once
```

2021-06-16 02:49 UTC, toji commented on layers-samples/proj-multiview.html
> +        is_multiview = true;
`is_multiview` doesn't currently seem to be used? Also, the render loop looks like it won't work unless multiview is available (which is fine for a sample like this) so perhaps we should either disable the "Enter VR" button or exit the session if we find that they don't have multiview support. Preferably with a error message on the page somewhere.

2021-07-08 00:35 UTC, fe1ixz commented on layers-samples/proj-multiview.html
> +Copyright 2018 The Immersive Web Community Group
Changed to 2021

2021-07-08 00:35 UTC, fe1ixz commented on layers-samples/proj-multiview.html
> +    function create_depth_texture(width, height) {
Removed function

2021-07-08 00:35 UTC, fe1ixz commented on layers-samples/proj-multiview.html
> +            if (views.length == 0) { // for mutliview we need to set fbo only once
Corrected typo

2021-07-08 00:39 UTC, fe1ixz commented on layers-samples/proj-multiview.html
> +        is_multiview = true;
Removed is_multiview, and added multiview compatibility check before user initiate immersive session, showing multiview compatibility status and disabling enter vr button if not compatible
![Screen Shot 2021-07-07 at 5 38 03 PM](https://user-images.githubusercontent.com/11973041/124844866-44d02e00-df4a-11eb-9240-c70a2f58df4b.png)

2021-07-08 21:56 UTC, toji commented
Thank you! As with the other sample I need to squash this one to merge it, but I don't think that will cause any problems.

2021-07-08 21:56 UTC, merged