Add anchor support to hittest sample
immersive-web/webxr-samples pull request #125
Opened 2021-07-07 22:23 UTC by lehoangphu

Anchor are mostly leveraged together with the hit-test. Thus, we should update the hittest sample to demonstrate the usage of Anchor and Hit-test together.

2021-07-16 22:49 UTC, toji reviewed
This is great, thank you!

I do have one request, though: You are correct that hit-tests are most useful with anchors, but since they CAN be used separately I'd like to keep the existing test the way it is to demonstrate "bare bones" hit test usage. If this test could be renamed to `hit-test-anchor.html` and put in the test list next to the original hit test sample, it would serve as a useful resource for developers to compare the two and better understand how anchors improve this use case. (It will also offer developers a simple way to A/B test a scenario with anchors and without, which will hopefully demonstrate why they're useful.)

2021-07-22 17:47 UTC, lehoangphu commented
Agree.  I put back hit-test.html and keep it together with the new hit-test-anchors.html

2021-08-03 20:58 UTC, toji requested changes
Thank you! I've requested a few minor, non-code updates but once that's been done I'm happy to land this.

2021-08-03 20:58 UTC, toji commented on hit-test-anchors.html
> +    <title>Hit Test</title>
```suggestion
    <title>Hit Test with Anchors</title>

```

2021-08-03 20:58 UTC, toji commented on hit-test-anchors.html
> +        <summary>Hit Test</summary>
```suggestion
        <summary>Hit Test with Anchors</summary>

```

2021-08-03 20:58 UTC, toji commented on hit-test-anchors.html
> +Copyright 2018 The Immersive Web Community Group
```suggestion
Copyright 2021 The Immersive Web Community Group

```

2021-08-03 20:58 UTC, toji commented on hit-test-anchors.html
> +          This sample demonstrates use of hit testing to place virtual objects on real-world surfaces.
Please update this description to indicate how this sample uses anchors.

2021-08-03 22:55 UTC, lehoangphu commented
Thank you for the feedbacks.  I have updated the title and description to better reflect the change.

2021-08-03 23:22 UTC, toji approved these changes

2021-08-03 23:23 UTC, merged

2021-08-03 23:23 UTC, toji commented
Thank you!