Add missing glClear call to layer samples
immersive-web/webxr-samples pull request #179
Opened 2024-01-25 20:21 UTC by idrisshah

Quad layer samples are broken because of missing glClear on Magic Leap system. These samples miss a glClear call before every frame rendered.

2024-01-25 21:42 UTC, cabanier commented
The extra `glclear` isn't necessary. The texture you get back from WebXR are supposed to be cleared already.
See https://immersive-web.github.io/layers/#xropaquetextures

2024-01-25 21:44 UTC, cabanier requested changes
This clear isn't needed. WebXR Textures are supposed to be cleared when you get them.
See https://immersive-web.github.io/layers/#xropaquetextures


I agree that this is not obvious from an implementor's point of view. It was hard to implement in a performant way

2024-01-26 17:23 UTC, idrisshah commented
Thanks for this clarification. I missed that part. In that case, there are some samples that still have glClear calls like: https://immersive-web.github.io/webxr-samples/layers-samples/proj-layer.html. Should those be cleaned up for consistency?

2024-01-26 17:44 UTC, cabanier commented
> Thanks for this clarification. I missed that part. In that case, there are some samples that still have glClear calls like: https://immersive-web.github.io/webxr-samples/layers-samples/proj-layer.html. Should those be cleaned up for consistency?

yes, that would be good

2025-05-07 15:02 UTC, closed without merging