added hands test file
immersive-web/webxr-samples pull request #77
Opened 2020-07-21 18:49 UTC by cabanier

This example shows basic use of the WebXR hands API.
If the device supports the feature, it will render your hands as a set of cubes.

2020-07-21 18:51 UTC, cabanier commented
FYI Oculus browser 10.2 supports this feature.
chrome://flags -> WebXR experiences with joint tracking -> set to 'Enabled' -> restart

2020-11-17 17:53 UTC, cabanier commented
@toji Can this be merged?

2020-11-20 23:52 UTC, toji requested changes
Apologies for not noticing this earlier. The sample looks good, but given that the API is still technically a WIP could we list this sample on the "Proposals" tab instead of the main sample list? At least until the API is more formally shipping.

The proposals tab actually just got re-enabled today by a different set of samples that @bialpio added, so it should be a pretty minor thing to move it over.

2020-11-20 23:52 UTC, toji commented on immersive-hands.html
> +Copyright 2018 The Immersive Web Community Group
```suggestion
Copyright 2020 The Immersive Web Community Group
```

2020-11-21 00:14 UTC, cabanier commented
> Apologies for not noticing this earlier. The sample looks good, but given that the API is still technically a WIP could we list this sample on the "Proposals" tab instead of the main sample list? At least until the API is more formally shipping.

No problem!

2020-11-21 03:12 UTC, toji commented
You'll need to move the test html file to the proposals folder as well, and make sure that any resources that it links to are updated to the right relative paths.

2020-11-21 15:45 UTC, toji approved these changes
Looks good, thanks! Github says there's a conflict, but we're good to merge once that's resolved.

2020-11-21 17:05 UTC, cabanier commented
There is no conflict :-)

2020-11-21 21:10 UTC, merged