Adding WebXR Layers samples
immersive-web/webxr-samples pull request #96
Opened 2021-03-09 08:23 UTC by felixtrz

This PR contains the new layer samples and all changes necessary to make it work. I have regrouped the changes and organized the commits to reflect the meaning of each change. This PR is to replace #89 @toji

2021-03-11 00:14 UTC, toji requested changes
Thank you for updating these! This pull request is MUCH easier to read, and I'm happy to see the merge conflicts have been resolved.

I'm still looking through the layers samples, since it's quite a bit of code, but wanted to mention a couple of things really quick: The fact that you were able to reduce this down to 4 well-focused commits is great, but I would actually prefer to see each of those commits posted as a separate pull request.

This is primarily so that feedback on one doesn't hold back the others. For example, from what I can see right now I would be inclined to merge the multiview and visibility blurred changes right away, but I can't do that because they're attached to the larger sample additions that I still have feedback on.

But again, thank you so much for cleaning up this pull request as much as you already have, and I'm looking forward to landing these changes!

2021-03-11 00:14 UTC, toji commented on immersive-hands.html
> +    function updateInputSources(session, frame, refSpace) {
As I mentioned in my comments on #89, I would like to see the comments in this file and the other samples updated to focus more the subject of the sample, like this function, and remove some of the large comment blocks that are repeated from other samples.

2021-03-24 22:46 UTC, fe1ixz commented on immersive-hands.html
> +    function updateInputSources(session, frame, refSpace) {
Thanks for the feedback, this particular sample has been removed as it is a duplicate to the immersive-hands sample in proposals. I have also removed the redundant comments from all layer samples except for projection layer sample, as all other samples are based on this one.

2021-05-11 23:22 UTC, fe1ixz commented
Closing in favor of smaller PRs: #105 #104

2021-05-11 23:22 UTC, closed without merging